version: '3.8'

services:
  postgres:
    image: postgres:12.16-bullseye
    container_name: 12.16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - ../dados_postgres/12:/var/lib/postgresql/data