version: '3.8'

services:
  postgres:
    image: postgres:12to13
    container_name: postgres12to13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - ../dados_postgres/12:/var/lib/postgresql/12
      - ../dados_postgres/13:/var/lib/postgresql/data